### ISSUE TITLE
Keyboard nav reaches Title in the wrong order when in Compact Card View.

### ISSUE THREAD

**Issue by tehstone** [MrJPGames/WayFarer-#30] opened 2019-10-29 16:35 UTC
Browser: Google Chrome

When in the compact view, entering ratings via keyboard skips from the overall rating to "historic/cultural" and then comes back to the title after "safe access."

This doesn't match with the way the items are laid out visually and is confusing.

**Comment by DragonBallZeke** [comment] 2019-10-29 18:37
I am also experiencing this issue

**Comment by MrJPGames** [comment] 2019-10-29 18:38
Duplicate of issue #21

**Closed by MrJPGames** 2019-10-29 18:38 UTC
