### ISSUE TITLE
Request: Open in OSM

### ISSUE THREAD

**Issue by fortepc** [MrJPGames/WayFarer-#82] opened 2019-12-12 18:00 UTC
**Describe the feature you'd like**
In the section for verifying location, add a button to open in Open Street Map, openstreetmap.org

**Describe reasons NOT to add this feature**
Adding too many buttons can clutter up the UI.

**Describe reasons to add this feature**
OSM is often more accurately mapped for things like nature trails and I often use it in my review process.

**Additional context**
OPR-Tools had this, and I think intel/gmap/osm are the best options to be able to to help a reviewer locate the nomination.

**Comment by MrJPGames** [comment] 2019-12-12 18:01
Duplicate of #47

**Comment by fortepc** [comment] 2019-12-12 18:02
ohhh, I thought that #47 was about the basemap tiles.

**Closed by MrJPGames** 2019-12-12 18:01 UTC
Labels: feature

**Comment by MrJPGames** [comment] 2019-12-12 18:05
That's actually not a bad idea, you could open an issue for that ;)
Though that feature would probably stay on the back-burner for quite some time.

**Comment by fortepc** [comment] 2019-12-12 18:11
I have no interest myself in custom basemap tiles :P I'll leave that for someone who does if that comes up lol. I don't mean to intentionally pile things on your plate.
